from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('users', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('name', sa.String(255)), sa.Column('email', sa.String(255), nullable=False), sa.Column('password_hash', sa.String(255)), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('interview_sessions', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id')), sa.Column('livekit_room_name', sa.String(255), unique=True), sa.Column('job_title', sa.String(255)), sa.Column('job_description', sa.Text()), sa.Column('experience_level', sa.String(100)), sa.Column('status', sa.String(50)), sa.Column('interview_plan', postgresql.JSONB), sa.Column('final_score', sa.Float()), sa.Column('final_report', postgresql.JSONB), sa.Column('started_at', sa.DateTime(timezone=True)), sa.Column('ended_at', sa.DateTime(timezone=True)), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('livekit_rooms', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_sessions.id')), sa.Column('room_name', sa.String(255), unique=True), sa.Column('participant_identity', sa.String(255)), sa.Column('metadata', postgresql.JSONB), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('interview_questions', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_sessions.id')), sa.Column('question_text', sa.Text(), nullable=False), sa.Column('skill', sa.String(120)), sa.Column('difficulty', sa.String(50)), sa.Column('expected_signals', postgresql.JSONB), sa.Column('order_index', sa.Integer()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('interview_answers', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_sessions.id')), sa.Column('question_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_questions.id')), sa.Column('transcript', sa.Text(), nullable=False), sa.Column('duration_seconds', sa.Integer()), sa.Column('confidence_score', sa.Float()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('interview_scores', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_sessions.id')), sa.Column('question_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_questions.id')), sa.Column('answer_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_answers.id')), sa.Column('technical_accuracy', sa.Integer()), sa.Column('clarity', sa.Integer()), sa.Column('depth', sa.Integer()), sa.Column('relevance', sa.Integer()), sa.Column('confidence', sa.Integer()), sa.Column('overall_score', sa.Float()), sa.Column('missing_points', postgresql.JSONB()), sa.Column('red_flags', postgresql.JSONB()), sa.Column('feedback', sa.Text()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('interview_events', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_sessions.id')), sa.Column('event_type', sa.String(100)), sa.Column('content', sa.Text()), sa.Column('metadata', postgresql.JSONB()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('documents', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id')), sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_sessions.id')), sa.Column('source_type', sa.String(100)), sa.Column('title', sa.String(255)), sa.Column('s3_key', sa.String(500)), sa.Column('content_text', sa.Text()), sa.Column('metadata', postgresql.JSONB()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('document_chunks', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('document_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('documents.id')), sa.Column('chunk_text', sa.Text()), sa.Column('embedding', Vector(1536)), sa.Column('metadata', postgresql.JSONB()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('tool_runs', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_sessions.id')), sa.Column('tool_name', sa.String(120)), sa.Column('input', postgresql.JSONB()), sa.Column('output', postgresql.JSONB()), sa.Column('latency_ms', sa.Integer()), sa.Column('status', sa.String(50)), sa.Column('error_message', sa.Text()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table('file_assets', sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True), sa.Column('user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id')), sa.Column('session_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('interview_sessions.id')), sa.Column('file_name', sa.String(255)), sa.Column('file_type', sa.String(100)), sa.Column('mime_type', sa.String(120)), sa.Column('s3_key', sa.String(500)), sa.Column('s3_url', sa.String(500)), sa.Column('metadata', postgresql.JSONB()), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()))

def downgrade() -> None:
    for t in ['file_assets','tool_runs','document_chunks','documents','interview_events','interview_scores','interview_answers','interview_questions','livekit_rooms','interview_sessions','users']:
        op.drop_table(t)
